libretro-mame: pre-create generated headers
Yay, more missing dependencies:
In file included from ../../../../../src/mame/audio/taito_zm.h:14,
                 from ../../../../../src/mame/drivers/zn.cpp:15:
../../../../../src/devices/cpu/tms57002/tms57002.h:208:10: fatal error: ../../emu/cpu/tms57002/tms57002.hxx: No such file or directory